"""initial schema

Revision ID: 2efc5bd8818d
Revises: 
Create Date: 2026-07-16 17:33:42.255366
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '2efc5bd8818d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.String(length=32), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_table('document_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.Column('publisher', sa.String(length=128), nullable=True),
    sa.Column('default_source_level', sa.Integer(), nullable=False),
    sa.Column('license_status', sa.String(length=24), nullable=False),
    sa.Column('retention_policy', sa.String(length=256), nullable=True),
    sa.Column('configured', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=48), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('run_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_idempotency_key'), 'ingestion_runs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_job_name'), 'ingestion_runs', ['job_name'], unique=False)
    op.create_table('manual_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stable_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=True),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('security_type', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stable_id')
    )
    op.create_index(op.f('ix_securities_cik'), 'securities', ['cik'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auth_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reconciled', sa.Boolean(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_actions_security_id'), 'corporate_actions', ['security_id'], unique=False)
    op.create_table('data_quality_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_issues_issue_type'), 'data_quality_issues', ['issue_type'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('url_canonical', sa.String(length=1024), nullable=False),
    sa.Column('url_original', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('publisher', sa.String(length=256), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_timezone', sa.String(length=48), nullable=True),
    sa.Column('source_level', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('simhash', sa.BigInteger(), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('license_state', sa.String(length=24), nullable=False),
    sa.Column('duplicate_family_id', sa.Integer(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_family_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['document_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_docs_sec_pub', 'documents', ['security_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_table('feature_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('asof_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('missing_fields', sa.JSON(), nullable=True),
    sa.Column('is_candidate', sa.Boolean(), nullable=False),
    sa.Column('candidate_reasons', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('pipeline_version', sa.String(length=16), nullable=False),
    sa.Column('config_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'snapshot_date', name='uq_snapshot')
    )
    op.create_index(op.f('ix_feature_snapshots_security_id'), 'feature_snapshots', ['security_id'], unique=False)
    op.create_index(op.f('ix_feature_snapshots_snapshot_date'), 'feature_snapshots', ['snapshot_date'], unique=False)
    op.create_table('market_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('bar_date', sa.Date(), nullable=False),
    sa.Column('session', sa.String(length=12), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('adjusted', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'bar_date', 'session', 'provider', name='uq_bar')
    )
    op.create_index('ix_bars_sec_date', 'market_bars', ['security_id', 'bar_date'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('rule', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('dedup_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    op.create_table('security_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=12), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('float_shares', sa.Float(), nullable=True),
    sa.Column('short_interest_shares', sa.Float(), nullable=True),
    sa.Column('short_interest_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_listings_security_id'), 'security_listings', ['security_id'], unique=False)
    op.create_index(op.f('ix_security_listings_ticker'), 'security_listings', ['ticker'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_items_security_id'), 'watchlist_items', ['security_id'], unique=False)
    op.create_table('ai_invocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=48), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_eur', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('predicate', sa.String(length=256), nullable=False),
    sa.Column('object', sa.String(length=512), nullable=False),
    sa.Column('figure', sa.String(length=128), nullable=True),
    sa.Column('claim_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confirmation_level', sa.Integer(), nullable=True),
    sa.Column('evidence_span', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('extracted_by', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_security_id'), 'claims', ['security_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('is_binary', sa.Boolean(), nullable=False),
    sa.Column('materiality', sa.String(length=8), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('announced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('classified_by', sa.String(length=16), nullable=False),
    sa.Column('classifier_confidence', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_security_id'), 'events', ['security_id'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('feature_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('risk_index', sa.Float(), nullable=True),
    sa.Column('squeeze_hazard', sa.Float(), nullable=True),
    sa.Column('squeeze_unknown', sa.Boolean(), nullable=False),
    sa.Column('execution_hazard', sa.Float(), nullable=True),
    sa.Column('dilution_risk', sa.Float(), nullable=True),
    sa.Column('confidence_grade', sa.String(length=1), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('gate_applied', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('main_contrary_evidence', sa.Text(), nullable=True),
    sa.Column('invalidation_conditions', sa.JSON(), nullable=True),
    sa.Column('missing_data', sa.JSON(), nullable=True),
    sa.Column('independent_origins', sa.Integer(), nullable=True),
    sa.Column('catalyst_type', sa.String(length=48), nullable=True),
    sa.Column('scoring_version', sa.String(length=16), nullable=False),
    sa.Column('config_hash', sa.String(length=16), nullable=False),
    sa.Column('code_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feature_snapshot_id'], ['feature_snapshots.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'score_date', name='uq_score')
    )
    op.create_index(op.f('ix_risk_scores_score_date'), 'risk_scores', ['score_date'], unique=False)
    op.create_index(op.f('ix_risk_scores_security_id'), 'risk_scores', ['security_id'], unique=False)
    op.create_index(op.f('ix_risk_scores_state'), 'risk_scores', ['state'], unique=False)
    op.create_table('claim_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('related_claim_id', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(length=16), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['related_claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'related_claim_id', 'relation', name='uq_claim_rel')
    )
    op.create_index(op.f('ix_claim_relations_claim_id'), 'claim_relations', ['claim_id'], unique=False)
    op.create_table('retrospective_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_score_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('reference_price', sa.Float(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('dd_intraday', sa.Float(), nullable=True),
    sa.Column('dd_close', sa.Float(), nullable=True),
    sa.Column('ret_close', sa.Float(), nullable=True),
    sa.Column('ret_vs_benchmark', sa.Float(), nullable=True),
    sa.Column('ret_vs_sector', sa.Float(), nullable=True),
    sa.Column('max_adverse_up', sa.Float(), nullable=True),
    sa.Column('hit_minus10', sa.Boolean(), nullable=True),
    sa.Column('hit_minus20', sa.Boolean(), nullable=True),
    sa.Column('hit_minus30', sa.Boolean(), nullable=True),
    sa.Column('hit_minus40', sa.Boolean(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_score_id', 'horizon_days', name='uq_retro')
    )
    op.create_index(op.f('ix_retrospective_outcomes_risk_score_id'), 'retrospective_outcomes', ['risk_score_id'], unique=False)
    op.create_index(op.f('ix_retrospective_outcomes_security_id'), 'retrospective_outcomes', ['security_id'], unique=False)
    op.create_table('score_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_score_id', sa.Integer(), nullable=False),
    sa.Column('component', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('missing', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_factors_risk_score_id'), 'score_factors', ['risk_score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_factors_risk_score_id'), table_name='score_factors')
    op.drop_table('score_factors')
    op.drop_index(op.f('ix_retrospective_outcomes_security_id'), table_name='retrospective_outcomes')
    op.drop_index(op.f('ix_retrospective_outcomes_risk_score_id'), table_name='retrospective_outcomes')
    op.drop_table('retrospective_outcomes')
    op.drop_index(op.f('ix_claim_relations_claim_id'), table_name='claim_relations')
    op.drop_table('claim_relations')
    op.drop_index(op.f('ix_risk_scores_state'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_security_id'), table_name='risk_scores')
    op.drop_index(op.f('ix_risk_scores_score_date'), table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_events_security_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_claims_security_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_table('ai_invocations')
    op.drop_index(op.f('ix_watchlist_items_security_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_security_listings_ticker'), table_name='security_listings')
    op.drop_index(op.f('ix_security_listings_security_id'), table_name='security_listings')
    op.drop_table('security_listings')
    op.drop_table('notifications')
    op.drop_index('ix_bars_sec_date', table_name='market_bars')
    op.drop_table('market_bars')
    op.drop_index(op.f('ix_feature_snapshots_snapshot_date'), table_name='feature_snapshots')
    op.drop_index(op.f('ix_feature_snapshots_security_id'), table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_index('ix_docs_sec_pub', table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_data_quality_issues_issue_type'), table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    op.drop_index(op.f('ix_corporate_actions_security_id'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_table('auth_sessions')
    op.drop_table('users')
    op.drop_index(op.f('ix_securities_cik'), table_name='securities')
    op.drop_table('securities')
    op.drop_table('manual_overrides')
    op.drop_index(op.f('ix_ingestion_runs_job_name'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_idempotency_key'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('document_sources')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
